import { Subject, TimetableEntry, PublishedTimetable } from '../types/timetable';

export const RVCE_COLLEGE_NAME = 'RV College of Engineering (RVCE)';
export const RVCE_BRANCH_NAME = 'Computer Science & Engineering';
export const RVCE_SEMESTER_NUMBER = 5;
export const RVCE_SECTION = 'D';
export const RVCE_ACADEMIC_YEAR = '2026–27';
export const RVCE_EFFECTIVE_DATE = '2026-09-07';
export const RVCE_DEFAULT_ROOM = 'CSE CRB 403';

export const RVCE_SUBJECTS: Subject[] = [
  {
    id: 'rvce_aiml',
    code: '22CS51',
    name: 'Artificial Intelligence & Machine Learning',
    type: 'THEORY',
    facultyName: 'Dr. K. Sharma',
    facultyEmail: 'ksharma@rvce.edu.in',
    credits: 4,
    room: 'CSE CRB 403',
  },
  {
    id: 'rvce_toc',
    code: '22CS52',
    name: 'Theory of Computation',
    type: 'THEORY',
    facultyName: 'Prof. S. Rao',
    facultyEmail: 'srao@rvce.edu.in',
    credits: 4,
    room: 'CSE CRB 403',
  },
  {
    id: 'rvce_dbms',
    code: '22CS53',
    name: 'Database Management Systems',
    type: 'THEORY',
    facultyName: 'Prof. V. Nambiar',
    facultyEmail: 'vnambiar@rvce.edu.in',
    credits: 4,
    room: 'CSE CRB 403',
  },
  {
    id: 'rvce_pome',
    code: '22HS54',
    name: 'Principles of Management & Economics',
    type: 'THEORY',
    facultyName: 'Prof. M. Mehta',
    facultyEmail: 'mmehta@rvce.edu.in',
    credits: 3,
    room: 'CSE CRB 403',
  },
  {
    id: 'rvce_adv_algo',
    code: '22CSE511',
    name: 'Advanced Algorithms',
    type: 'ELECTIVE',
    facultyName: 'Dr. A. Verma',
    facultyEmail: 'averma@rvce.edu.in',
    credits: 3,
    room: 'CSE CRB 403',
    isElective: true,
    electiveGroup: 'ELECTIVE_1',
    isSelectedElective: true, // Selected default elective for Elective I group
  },
  {
    id: 'rvce_nlp',
    code: '22CSE512',
    name: 'Natural Language Processing',
    type: 'ELECTIVE',
    facultyName: 'Dr. P. Nair',
    facultyEmail: 'pnair@rvce.edu.in',
    credits: 3,
    room: 'CSE CRB 403',
    isElective: true,
    electiveGroup: 'ELECTIVE_1',
    isSelectedElective: false, // Alternate elective option in Elective I group
  },
  {
    id: 'rvce_aiml_lab',
    code: '22CS51L',
    name: 'AIML Laboratory',
    type: 'LAB',
    facultyName: 'Dr. K. Sharma & Team',
    credits: 1.5,
    room: 'CRB Lab 2',
  },
  {
    id: 'rvce_dbms_lab',
    code: '22CS53L',
    name: 'DBMS Laboratory',
    type: 'LAB',
    facultyName: 'Prof. V. Nambiar & Team',
    credits: 1.5,
    room: 'CRB Lab 1',
  },
  {
    id: 'rvce_toc_tut',
    code: '22CS52T',
    name: 'TOC Tutorial',
    type: 'TUTORIAL',
    facultyName: 'Prof. S. Rao',
    credits: 1,
    room: 'CSE CRB 403',
    parentSubjectId: 'rvce_toc', // Tutorial belongs to TOC Theory (22CS52), NOT counted separately
  },
];

export const RVCE_TIMETABLE_ENTRIES: TimetableEntry[] = [
  // MONDAY
  {
    id: 'e_mon_1',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_dbms',
    subjectName: 'Database Management Systems',
    courseCode: '22CS53',
    dayOfWeek: 'MONDAY',
    startTime: '09:00',
    endTime: '10:00',
    room: 'CSE CRB 403',
    type: 'THEORY',
    facultyName: 'Prof. V. Nambiar',
  },
  {
    id: 'e_mon_2',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_aiml',
    subjectName: 'Artificial Intelligence & Machine Learning',
    courseCode: '22CS51',
    dayOfWeek: 'MONDAY',
    startTime: '10:00',
    endTime: '11:00',
    room: 'CSE CRB 403',
    type: 'THEORY',
    facultyName: 'Dr. K. Sharma',
  },
  {
    id: 'e_mon_3',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_toc',
    subjectName: 'Theory of Computation',
    courseCode: '22CS52',
    dayOfWeek: 'MONDAY',
    startTime: '11:30',
    endTime: '12:30',
    room: 'CSE CRB 403',
    type: 'THEORY',
    facultyName: 'Prof. S. Rao',
  },
  {
    id: 'e_mon_4',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_pome',
    subjectName: 'Principles of Management & Economics',
    courseCode: '22HS54',
    dayOfWeek: 'MONDAY',
    startTime: '13:30',
    endTime: '14:30',
    room: 'CSE CRB 403',
    type: 'THEORY',
    facultyName: 'Prof. M. Mehta',
  },

  // TUESDAY
  {
    id: 'e_tue_1',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_adv_algo',
    subjectName: 'Advanced Algorithms (Elective I)',
    courseCode: '22CSE511',
    dayOfWeek: 'TUESDAY',
    startTime: '09:00',
    endTime: '10:00',
    room: 'CSE CRB 403',
    type: 'ELECTIVE',
    facultyName: 'Dr. A. Verma',
  },
  {
    id: 'e_tue_2',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_nlp',
    subjectName: 'Natural Language Processing (Elective II)',
    courseCode: '22CSE512',
    dayOfWeek: 'TUESDAY',
    startTime: '10:00',
    endTime: '11:00',
    room: 'CSE CRB 403',
    type: 'ELECTIVE',
    facultyName: 'Dr. P. Nair',
  },
  {
    id: 'e_tue_3',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_dbms_lab',
    subjectName: 'DBMS Laboratory',
    courseCode: '22CS53L',
    dayOfWeek: 'TUESDAY',
    startTime: '11:30',
    endTime: '13:30',
    room: 'CRB Lab 1',
    type: 'LAB',
    facultyName: 'Prof. V. Nambiar',
  },
  {
    id: 'e_tue_4',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_toc',
    subjectName: 'Theory of Computation',
    courseCode: '22CS52',
    dayOfWeek: 'TUESDAY',
    startTime: '14:30',
    endTime: '15:30',
    room: 'CSE CRB 403',
    type: 'THEORY',
    facultyName: 'Prof. S. Rao',
  },

  // WEDNESDAY
  {
    id: 'e_wed_1',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_aiml',
    subjectName: 'Artificial Intelligence & Machine Learning',
    courseCode: '22CS51',
    dayOfWeek: 'WEDNESDAY',
    startTime: '09:00',
    endTime: '10:00',
    room: 'CSE CRB 403',
    type: 'THEORY',
    facultyName: 'Dr. K. Sharma',
  },
  {
    id: 'e_wed_2',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_dbms',
    subjectName: 'Database Management Systems',
    courseCode: '22CS53',
    dayOfWeek: 'WEDNESDAY',
    startTime: '10:00',
    endTime: '11:00',
    room: 'CSE CRB 403',
    type: 'THEORY',
    facultyName: 'Prof. V. Nambiar',
  },
  {
    id: 'e_wed_3',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_aiml_lab',
    subjectName: 'AIML Laboratory',
    courseCode: '22CS51L',
    dayOfWeek: 'WEDNESDAY',
    startTime: '11:30',
    endTime: '13:30',
    room: 'CRB Lab 2',
    type: 'LAB',
    facultyName: 'Dr. K. Sharma',
  },

  // THURSDAY
  {
    id: 'e_thu_1',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_pome',
    subjectName: 'Principles of Management & Economics',
    courseCode: '22HS54',
    dayOfWeek: 'THURSDAY',
    startTime: '09:00',
    endTime: '10:00',
    room: 'CSE CRB 403',
    type: 'THEORY',
    facultyName: 'Prof. M. Mehta',
  },
  {
    id: 'e_thu_2',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_toc',
    subjectName: 'Theory of Computation',
    courseCode: '22CS52',
    dayOfWeek: 'THURSDAY',
    startTime: '10:00',
    endTime: '11:00',
    room: 'CSE CRB 403',
    type: 'THEORY',
    facultyName: 'Prof. S. Rao',
  },
  {
    id: 'e_thu_3',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_adv_algo',
    subjectName: 'Advanced Algorithms (Elective I)',
    courseCode: '22CSE511',
    dayOfWeek: 'THURSDAY',
    startTime: '11:30',
    endTime: '12:30',
    room: 'CSE CRB 403',
    type: 'ELECTIVE',
    facultyName: 'Dr. A. Verma',
  },
  {
    id: 'e_thu_4',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_toc_tut',
    subjectName: 'TOC Tutorial',
    courseCode: '22CS52T',
    dayOfWeek: 'THURSDAY',
    startTime: '13:30',
    endTime: '14:30',
    room: 'CSE CRB 403',
    type: 'TUTORIAL',
    facultyName: 'Prof. S. Rao',
  },

  // FRIDAY
  {
    id: 'e_fri_1',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_aiml',
    subjectName: 'Artificial Intelligence & Machine Learning',
    courseCode: '22CS51',
    dayOfWeek: 'FRIDAY',
    startTime: '09:00',
    endTime: '10:00',
    room: 'CSE CRB 403',
    type: 'THEORY',
    facultyName: 'Dr. K. Sharma',
  },
  {
    id: 'e_fri_2',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_dbms',
    subjectName: 'Database Management Systems',
    courseCode: '22CS53',
    dayOfWeek: 'FRIDAY',
    startTime: '10:00',
    endTime: '11:00',
    room: 'CSE CRB 403',
    type: 'THEORY',
    facultyName: 'Prof. V. Nambiar',
  },
  {
    id: 'e_fri_3',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_nlp',
    subjectName: 'Natural Language Processing (Elective II)',
    courseCode: '22CSE512',
    dayOfWeek: 'FRIDAY',
    startTime: '11:30',
    endTime: '12:30',
    room: 'CSE CRB 403',
    type: 'ELECTIVE',
    facultyName: 'Dr. P. Nair',
  },
  {
    id: 'e_fri_4',
    timetableId: 'pub_rvce_5_d',
    subjectId: 'rvce_pome',
    subjectName: 'Principles of Management & Economics',
    courseCode: '22HS54',
    dayOfWeek: 'FRIDAY',
    startTime: '13:30',
    endTime: '14:30',
    room: 'CSE CRB 403',
    type: 'THEORY',
    facultyName: 'Prof. M. Mehta',
  },
];

export const RVCE_PUBLISHED_TIMETABLE: PublishedTimetable = {
  id: 'pub_rvce_5_d',
  collegeId: 'rvce',
  collegeName: RVCE_COLLEGE_NAME,
  programId: 'cse',
  branchName: RVCE_BRANCH_NAME,
  semesterNumber: RVCE_SEMESTER_NUMBER,
  section: RVCE_SECTION,
  academicYear: RVCE_ACADEMIC_YEAR,
  effectiveFrom: RVCE_EFFECTIVE_DATE,
  subjects: RVCE_SUBJECTS,
  entries: RVCE_TIMETABLE_ENTRIES,
};
